services:
  postgres:
    image: postgres:17

    container_name: teamflow-postgres

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: teamflow_billing

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./backend

    container_name: teamflow-backend

    restart: always

    ports:
      - "5000:5000"

    environment:
      PORT: 5000

      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: teamflow_billing
      DB_USER: postgres
      DB_PASSWORD: postgres

    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:5000

    container_name: teamflow-frontend

    restart: always

    ports:
      - "5173:80"

    depends_on:
      - backend


volumes:
  postgres_data: